# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "iPhone 8",
   "iPhone 8 Plus",
   "iPhone 11 Pro Max",
   "iPad Pro (12.9-inch) (4th generation)"
])

languages([
  "cs",
  "de-DE",
  "el",
  "en-US",
  "es-ES",
  "fr-FR",
  "it",
  "ja",
  "nl-NL",
  "pl",
  "pt-BR",
  "ru",
  "sr",
  "tr-TR",
  "vi",
  "zh-Hant",
  "zh-Hans"
])

# The name of the scheme which contains the UI Tests
# scheme("SchemeName")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
